### ISSUE TITLE
Fixed energy density

### ISSUE THREAD

**Issue by AdamRJensen** [jranalli/solarspatialtools#15]
https://github.com/jranalli/solarspatialtools/blob/6cc100812662f9319de72ebceed29294fde65621/joss2024/paper.md?plain=1#L29

The statement "earth's surface with a fixed energy density" seems questionable. The energy density varies significantly diurnally and with cloud cover. Maybe I'm misunderstanding the sentence?

**Comment by AdamRJensen** [comment]
Maybe instead say "with a relative low energy density"

**Comment by jranalli** [comment]
The intent was to say that the solar energy resource density is determined by factors outside of our control and, unlike fossil fuels for example, we can't transport it all to a big central generation facility; to generate more power, we need to add more widely distributed collector area. 

But I think your phrasing would make sense as a way of explaining the point, so I changed it in the latest [commit](https://github.com/jranalli/solarspatialtools/commit/9079ef0cc18244c823f4104406bd1f5f8a982001).

**Comment by jranalli** [comment]
I saw you closed the other paper text comment, so I'm going to assume this was ok as well. Happy to keep editing if you have continued concerns with the new phrasing.
