### ISSUE TITLE
Package vs sub-package

### ISSUE THREAD

**Issue by AdamRJensen** [jranalli/solarspatialtools#16]
https://github.com/jranalli/solarspatialtools/blob/6cc100812662f9319de72ebceed29294fde65621/joss2024/paper.md?plain=1#L39

You write "are contained in the following packages" - aren't these sub-packages or modules?

**Comment by jranalli** [comment]
Good catch, I made this consistent in the latest [commit for that branch](https://github.com/jranalli/solarspatialtools/commit/9079ef0cc18244c823f4104406bd1f5f8a982001).
