### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by AdamRJensen** [jranalli/solarspatialtools#22]
When I run the test suite in a windows python 3.12 environment, I get a bunch of failures:

![image](https://github.com/user-attachments/assets/59f513bd-a97b-4b91-b9aa-34dccc99ef9e)

@jranalli could you try and see if you can replicate this?

**Comment by jranalli** [comment]
I can try. Before I dig too far, is there a chance that this is related to the numpy, etc. packages not having been pinned? I know some of the tests were failing on that before. I just merged the dev branch that had those pin values in it, so the latest main commit should be good for testing.

**Comment by jranalli** [comment]
OK I think I was able to replicate. I believe it's just a relative filepath issue. My tests are reusing data files used by the demos, so in my case, I was able to get your error pattern if I ran `pytest` from the project root directory. But if I changed into the tests directory, it ran correctly.

`c:\<somepath>\solarspatialtools\pytest`
![image](https://github.com/user-attachments/assets/5fe3fe6f-5966-45c6-abea-0964b5a25630)

`c:\<somepath>\solarspatialtools\tests\pytest`
![image](https://github.com/user-attachments/assets/eda5768c-426d-4351-9691-3a0c7e8a71ce)

**Comment by AdamRJensen** [comment]
> OK I think I was able to replicate. I believe it's just a relative filepath issue. My tests are reusing data files used by the demos, so in my case, I was able to get your error pattern if I ran `pytest` from the project root directory. But if I changed into the tests directory, it ran correctly.

Changing the directory did indeed solve that. I can't tell if that was me being silly or a poor design.. anyhow, thanks for looking into it 😄

**Comment by jranalli** [comment]
It's quite possibly poor design on my part. I am not good at getting that kind of stuff working correctly outside my own workflow. As long as the CI build is working I try to just accommodate that.
