### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by AdamRJensen** [jranalli/solarspatialtools#23]
When I run the test suite, there are several warnings raised about deprecated functions.

It would be nice to update these functions, such that the package will need less maintenance down the road.

**Comment by AdamRJensen** [comment]
One culprit is the use of `pd.TimedeltaIndex` which is deprecated.

**Comment by jranalli** [comment]
Alright I've got all these deprecation warnings removed from the tests, [for example here](https://github.com/jranalli/solarspatialtools/actions/runs/10864206290/job/30149221361).

The only warning thrown is one that deals with calculations involving NaN, but it's expected based on inputs.
